# Generated by Django 4.2 on 2024-01-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_alter_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="slug",
        ),
    ]
