# Generated by Django 4.2 on 2024-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0005_remove_task_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
